project:
  type: website
  output-dir: docs

website:
  title: "ML-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - ML_notebook.qmd
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



